### ISSUE TITLE
thegraph_rai.ipynb doesn't execute

### ISSUE THREAD

**Issue by BenSchZA** [cadCAD-org/snippets#4]
The notebook [thegraph_rai.ipynb](thegraph_rai.ipynb) doesn't execute. I attempted to update it, but wasn't quite sure of the intention of some of the operations. Because there's a CI test-suite, we could use that to make sure only notebooks that work can be merged, and that the static website generation script workflow passes.

@markusbkoch @mzargham I believe it's your notebook :)

**Comment by markusbkoch** [comment]
Looks like it's @danlessa's?
https://github.com/cadCAD-org/snippets/commits/main/snippets/thegraph_rai.ipynb

**Comment by danlessa** [comment]
removed that snippet for now
